"""Detection signals.

Signal 1 (this milestone) is the Groq LLM read. It reads the passage the way a
person would and returns a single probability that the text is AI generated, plus
a short reason we keep for the audit log. Signal 2 (stylometry) arrives in
Milestone 4.
"""
import json
import os

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a text provenance analyst. You judge whether a passage of writing was "
    "most likely written by a human or generated by an AI language model. Weigh tone, "
    "specific lived detail, natural imperfection, rhythm, and whether the phrasing "
    "feels generic and evenly polished. Formal writing or writing from a non native "
    "English speaker is not by itself a sign of AI, so do not penalize it for that. "
    "Return ONLY a JSON object with two keys: 'p_ai', a number from 0 to 1 giving the "
    "probability the text was AI generated (0 means clearly human, 1 means clearly AI), "
    "and 'reason', a short phrase under 20 words naming the main cue. No other text."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def groq_signal(text):
    """Return {'p_ai': float 0..1, 'reason': str}.

    On any failure (missing key, network, bad JSON) it falls back to 0.5, which
    lands in the uncertain band. That is the safe default: when the signal cannot
    speak, the system does not accuse anyone.
    """
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        p_ai = float(data.get("p_ai"))
        p_ai = min(1.0, max(0.0, p_ai))
        reason = str(data.get("reason", ""))[:300]
        return {"p_ai": round(p_ai, 3), "reason": reason}
    except Exception as e:
        return {"p_ai": 0.5, "reason": f"signal unavailable, defaulted to uncertain ({e})"}
