"""Detection signals.

Signal 1 is the Groq LLM read: it reads the passage the way a person would and
returns a single probability that the text is AI generated, plus a short reason
for the audit log. Signal 2 is stylometry: plain statistics about the writing
style, computed with no external libraries.
"""
import json
import math
import os
import re

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a careful text provenance analyst. Estimate the probability that a passage "
    "was generated by an AI language model rather than written by a human.\n\n"
    "AI tells that push the score up: formulaic transitions like 'Furthermore', "
    "'Moreover', or 'It is important to note'; evenly polished, uniform sentences; "
    "balanced 'on one hand / on the other' hedging with no personal stance; generic "
    "claims with no specific lived detail; vague appeals to authority like 'studies "
    "show' with nothing concrete; list-like or templated structure.\n\n"
    "Human tells that push the score down: specific personal or sensory detail, a "
    "strong or idiosyncratic voice, casual register, opinions grounded in real "
    "experience, small imperfections, and surprising word choices.\n\n"
    "The single strongest AI signal is fluent, confident prose that conveys little "
    "concrete substance. Specific, substantive, domain grounded analysis with real "
    "checkable claims leans human even in a formal register, because AI filler avoids "
    "committing to concrete claims.\n\n"
    "Rules: Formal, academic, or polished writing is NOT by itself evidence of AI. "
    "Plenty of humans write that way, including non native English speakers, so do not "
    "raise the score for formality alone. Reserve scores above 0.7 for text with clear "
    "AI tells and little specific substance. Use the middle (0.4 to 0.6) when the text "
    "mixes both or you are genuinely unsure. Falsely accusing a real writer is costly, "
    "so when in doubt, lean lower.\n\n"
    "Return ONLY a JSON object: {\"p_ai\": number 0 to 1, \"reason\": short phrase under "
    "20 words naming the main cue}. No other text."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def groq_signal(text):
    """Return {'p_ai': float 0..1, 'reason': str}.

    On any failure (missing key, network, bad JSON) it falls back to 0.5, which
    lands in the uncertain band. That is the safe default: when the signal cannot
    speak, the system does not accuse anyone.
    """
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = json.loads(resp.choices[0].message.content)
        p_ai = float(data.get("p_ai"))
        p_ai = min(1.0, max(0.0, p_ai))
        reason = str(data.get("reason", ""))[:300]
        return {"p_ai": round(p_ai, 3), "reason": reason}
    except Exception as e:
        return {"p_ai": 0.5, "reason": f"signal unavailable, defaulted to uncertain ({e})"}


# --- Signal 2: stylometry --------------------------------------------------
#
# Three plain statistics that tend to differ between uniform machine text and
# more variable human text. Each maps to a 0..1 "AI-ness" sub score by a linear
# ramp between a human anchor and an AI anchor. The signal score is their mean.
# The anchors below were tuned against the four calibration inputs in M4.

# Punctuation beyond the ubiquitous period and comma. Humans reach for these
# more; AI prose tends to stay plain.
_EXPRESSIVE_PUNCT = set(";:!?()\"'-–—…")


def _split_sentences(text):
    parts = re.split(r"[.!?]+(?:\s|$)", text.strip())
    return [p for p in (s.strip() for s in parts) if p]


def _words(text):
    return re.findall(r"[a-z0-9']+", text.lower())


def _coefficient_of_variation(values):
    n = len(values)
    if n < 2:
        return None
    mean = sum(values) / n
    if mean == 0:
        return None
    var = sum((v - mean) ** 2 for v in values) / n
    return math.sqrt(var) / mean


def _mattr(tokens, window=40):
    """Moving average type token ratio. Averaging fixed size windows keeps the
    diversity measure stable across texts of different length."""
    n = len(tokens)
    if n == 0:
        return 0.0
    if n <= window:
        return len(set(tokens)) / n
    ratios = [
        len(set(tokens[i : i + window])) / window
        for i in range(n - window + 1)
    ]
    return sum(ratios) / len(ratios)


def _ramp(value, human_anchor, ai_anchor):
    """Map a metric to 0..1 AI-ness. value at human_anchor -> 0.0, at
    ai_anchor -> 1.0, clamped outside that range."""
    if human_anchor == ai_anchor:
        return 0.5
    frac = (human_anchor - value) / (human_anchor - ai_anchor)
    return max(0.0, min(1.0, frac))


def stylometry_signal(text):
    """Return {'p_ai': float 0..1, ...per metric detail...}.

    On very short text the statistics are too noisy to trust, so the signal
    stays neutral at 0.5 and lets the LLM lead (see the short text edge case in
    planning.md).
    """
    sentences = _split_sentences(text)
    tokens = _words(text)

    if len(sentences) < 2 or len(tokens) < 30:
        return {
            "p_ai": 0.5,
            "note": "short text, stylometry neutralized",
            "sentence_cv": None, "mattr": None, "punct_distinct": None,
            "cv_sub": None, "mattr_sub": None, "punct_sub": None,
        }

    cv = _coefficient_of_variation([len(s.split()) for s in sentences])
    mattr = _mattr(tokens)
    punct_distinct = len(_EXPRESSIVE_PUNCT.intersection(set(text)))

    # AI text is more uniform: lower sentence variation, less diverse vocabulary,
    # plainer punctuation. Each of those pushes the sub score toward 1.0.
    cv_sub = _ramp(cv, human_anchor=0.6, ai_anchor=0.25) if cv is not None else 0.5
    mattr_sub = _ramp(mattr, human_anchor=0.95, ai_anchor=0.65)
    punct_sub = _ramp(punct_distinct, human_anchor=3, ai_anchor=0)

    p_ai = round((cv_sub + mattr_sub + punct_sub) / 3, 3)
    return {
        "p_ai": p_ai,
        "note": "",
        "sentence_cv": round(cv, 3) if cv is not None else None,
        "mattr": round(mattr, 3),
        "punct_distinct": punct_distinct,
        "cv_sub": round(cv_sub, 3),
        "mattr_sub": round(mattr_sub, 3),
        "punct_sub": round(punct_sub, 3),
    }
